# This is a basic workflow to help you get started with Actions

name: LinkedIn Java OAuth Lib Validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/checkout@v2
    
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Super-Linter
        uses: github/super-linter@v4.6.1
        env: 
          GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
          VALIDATE_JAVA : true

      # Runs a spring boot server and test cases
      - name: Build and Run Tests for client
        working-directory: ./client
        run: mvn spring-boot:run
      
      # Runs a spring boot server and test cases
      - name: Build and Run Tests for server
        working-directory: ./server
        run: mvn spring-boot:run

          

